# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ButtonPanel(object):
    def setupUi(self, ButtonPanel):
        ButtonPanel.setObjectName("ButtonPanel")
        ButtonPanel.resize(1000, 41)
        ButtonPanel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalLayout = QtWidgets.QHBoxLayout(ButtonPanel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.car_detection_button = QtWidgets.QPushButton(ButtonPanel)
        self.car_detection_button.setObjectName("car_detection_button")
        self.horizontalLayout.addWidget(self.car_detection_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.people_detection_button = QtWidgets.QPushButton(ButtonPanel)
        self.people_detection_button.setObjectName("people_detection_button")
        self.horizontalLayout.addWidget(self.people_detection_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.car_monitor_button = QtWidgets.QPushButton(ButtonPanel)
        self.car_monitor_button.setObjectName("car_monitor_button")
        self.horizontalLayout.addWidget(self.car_monitor_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.people_monitor_button = QtWidgets.QPushButton(ButtonPanel)
        self.people_monitor_button.setObjectName("people_monitor_button")
        self.horizontalLayout.addWidget(self.people_monitor_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.modify_info_button = QtWidgets.QPushButton(ButtonPanel)
        self.modify_info_button.setObjectName("modify_info_button")
        self.horizontalLayout.addWidget(self.modify_info_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.exit_button = QtWidgets.QPushButton(ButtonPanel)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)

        self.retranslateUi(ButtonPanel)
        QtCore.QMetaObject.connectSlotsByName(ButtonPanel)

    def retranslateUi(self, ButtonPanel):
        _translate = QtCore.QCoreApplication.translate
        self.car_detection_button.setText(_translate("ButtonPanel", "车流量检测"))
        self.people_detection_button.setText(_translate("ButtonPanel", "人流量检测"))
        self.car_monitor_button.setText(_translate("ButtonPanel", "车流量监控管理"))
        self.people_monitor_button.setText(_translate("ButtonPanel", "人流量监控管理"))
        self.modify_info_button.setText(_translate("ButtonPanel", "修改个人信息"))
        self.exit_button.setText(_translate("ButtonPanel", "退出"))
