# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CarMonitorPage(object):
    def setupUi(self, CarMonitorPage):
        CarMonitorPage.setObjectName("CarMonitorPage")
        CarMonitorPage.resize(748, 474)
        self.mainLayout = QtWidgets.QHBoxLayout(CarMonitorPage)
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.table = QtWidgets.QTableWidget(CarMonitorPage)
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.leftLayout.addWidget(self.table)
        self.addButton = QtWidgets.QPushButton(CarMonitorPage)
        self.addButton.setObjectName("addButton")
        self.leftLayout.addWidget(self.addButton)
        self.mainLayout.addLayout(self.leftLayout)

        # Set column widths
        self.table.setColumnWidth(0, 200)  # 设置第一列宽度
        self.table.setColumnWidth(1, 200)  # 设置第二列宽度
        self.table.setColumnWidth(2, 200)  # 设置第三列宽度
        self.table.setColumnWidth(3, 800)  # 设置第四列宽度

        self.retranslateUi(CarMonitorPage)
        QtCore.QMetaObject.connectSlotsByName(CarMonitorPage)

    def retranslateUi(self, CarMonitorPage):
        _translate = QtCore.QCoreApplication.translate
        CarMonitorPage.setWindowTitle(_translate("CarMonitorPage", "Car Monitor Page"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("CarMonitorPage", "名字"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("CarMonitorPage", "修改名字"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("CarMonitorPage", "删除监控"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("CarMonitorPage", "地址"))
        self.addButton.setText(_translate("CarMonitorPage", "增加监控"))
