# import statements
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QFormLayout, QLabel, QLineEdit, QPushButton, QSpacerItem, QSizePolicy, QMessageBox
from PyQt5 import QtCore

class Ui_ModifyInfoPage(object):
    def setupUi(self, ModifyInfoPage):
        ModifyInfoPage.setObjectName("ModifyInfoPage")
        ModifyInfoPage.resize(400, 300)
        self.mainLayout = QVBoxLayout(ModifyInfoPage)
        self.mainLayout.setObjectName("mainLayout")
        spacerItem = QSpacerItem(QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QLabel(ModifyInfoPage)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.usernameLabel)
        self.usernameEdit = QLineEdit(ModifyInfoPage)
        self.usernameEdit.setObjectName("usernameEdit")
        self.usernameEdit.setReadOnly(True)  # Usernames should not be editable
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.usernameEdit)
        self.passwordLabel = QLabel(ModifyInfoPage)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.passwordLabel)
        self.passwordEdit = QLineEdit(ModifyInfoPage)
        self.passwordEdit.setEchoMode(QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.passwordEdit)
        self.securityQuestionLabel = QLabel(ModifyInfoPage)
        self.securityQuestionLabel.setObjectName("securityQuestionLabel")
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.securityQuestionLabel)
        self.securityQuestionEdit = QLineEdit(ModifyInfoPage)
        self.securityQuestionEdit.setObjectName("securityQuestionEdit")
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.securityQuestionEdit)
        self.securityAnswerLabel = QLabel(ModifyInfoPage)
        self.securityAnswerLabel.setObjectName("securityAnswerLabel")
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.securityAnswerLabel)
        self.securityAnswerEdit = QLineEdit(ModifyInfoPage)
        self.securityAnswerEdit.setObjectName("securityAnswerEdit")
        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.securityAnswerEdit)
        self.mainLayout.addLayout(self.formLayout)
        self.buttonLayout = QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QSpacerItem(QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.submitButton = QPushButton(ModifyInfoPage)
        self.submitButton.setObjectName("submitButton")
        self.buttonLayout.addWidget(self.submitButton)
        spacerItem2 = QSpacerItem(QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.mainLayout.addLayout(self.buttonLayout)
        spacerItem3 = QSpacerItem(QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem3)

        self.retranslateUi(ModifyInfoPage)
        QtCore.QMetaObject.connectSlotsByName(ModifyInfoPage)

    def retranslateUi(self, ModifyInfoPage):
        _translate = QtCore.QCoreApplication.translate
        ModifyInfoPage.setWindowTitle(_translate("ModifyInfoPage", "Modify Info Page"))
        self.usernameLabel.setText(_translate("ModifyInfoPage", "账号:"))
        self.passwordLabel.setText(_translate("ModifyInfoPage", "密码:"))
        self.securityQuestionLabel.setText(_translate("ModifyInfoPage", "密保问题:"))
        self.securityAnswerLabel.setText(_translate("ModifyInfoPage", "密保答案:"))
        self.submitButton.setText(_translate("ModifyInfoPage", "提交"))
