# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'people_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PeopleMonitorPage(object):
    def setupUi(self, PeopleMonitorPage):
        PeopleMonitorPage.setObjectName("PeopleMonitorPage")
        PeopleMonitorPage.resize(1600, 1200)
        self.mainLayout = QtWidgets.QHBoxLayout(PeopleMonitorPage)
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.table = QtWidgets.QTableWidget(PeopleMonitorPage)
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.leftLayout.addWidget(self.table)
        self.addButton = QtWidgets.QPushButton(PeopleMonitorPage)
        self.addButton.setObjectName("addButton")
        self.leftLayout.addWidget(self.addButton)
        self.mainLayout.addLayout(self.leftLayout)
        # Set column widths
        self.table.setColumnWidth(0, 200)  # 设置第一列宽度
        self.table.setColumnWidth(1, 200)  # 设置第二列宽度
        self.table.setColumnWidth(2, 200)  # 设置第三列宽度
        self.table.setColumnWidth(3, 800)  # 设置第四列宽度

        self.retranslateUi(PeopleMonitorPage)
        QtCore.QMetaObject.connectSlotsByName(PeopleMonitorPage)

    def retranslateUi(self, PeopleMonitorPage):
        _translate = QtCore.QCoreApplication.translate
        PeopleMonitorPage.setWindowTitle(_translate("PeopleMonitorPage", "People Monitor Page"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("PeopleMonitorPage", "名字"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("PeopleMonitorPage", "修改名字"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("PeopleMonitorPage", "删除监控"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("PeopleMonitorPage", "地址"))
        self.addButton.setText(_translate("PeopleMonitorPage", "增加监控"))
